#!/bin/bash

# Quick RGB Testnet Setup Commands
echo "🚀 Quick RGB Testnet Setup"
echo "========================="
echo ""
echo "Run these commands on your VPS:"
echo ""
echo "# 1. Install RGB CLI (if not installed)"
echo "curl -sSL https://rgb.tech/install.sh | sh"
echo ""
echo "# 2. Create testnet wallet"
echo "rgb-cli --network testnet wallet create --name lightcat_test"
echo ""
echo "# 3. Issue test tokens"
echo "rgb-cli --network testnet issue \\"
echo "  --wallet lightcat_test \\"
echo "  --ticker TCAT \\"
echo "  --name 'TestCat' \\"
echo "  --supply 21000000"
echo ""
echo "# 4. Update API configuration"
echo "nano /root/lightcat-api/.env"
echo "# Change: USE_MOCK_RGB=false"
echo "# Change: RGB_NETWORK=testnet"
echo ""
echo "# 5. Restart API"
echo "systemctl restart lightcat-api"
echo ""
echo "# 6. Test it!"
echo "curl -X POST https://rgblightcat.com/api/rgb/invoice \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"rgbInvoice\": \"rgb:utxob:test\", \"batchCount\": 1}'"